services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  product-service:
    build: ./product-service
    image: product-service:latest
    container_name: product-service
    hostname: product-service
    ports:
      - "8083:8080"
    networks:
      - my_network
    environment:
      SPRING_RABBITMQ_HOST: 'rabbitmq'
      SPRING_RABBITMQ_PORT: 5672
      SPRING_PROFILES_ACTIVE: 'dev'
    depends_on:
      - rabbitmq

  order-service:
    build: ./order-service
    image: order-service:latest
    container_name: order-service
    hostname: order-service
    ports:
      - "8084:8080"
    networks:
      - my_network
    environment:
      SPRING_RABBITMQ_HOST: 'rabbitmq'
      SPRING_RABBITMQ_PORT: 5672
      SPRING_PROFILES_ACTIVE: 'dev'
    depends_on:
      - rabbitmq

  postgres:
    image: 'postgres:15'
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  rabbitmq_data:
  postgres_data:

networks:
  my_network:
    driver: bridge
